gravitational/workshop

k8sprod.md

(proposal) Added note about compile time vs runtime libraries dependencies

Add note about shared libs vs statically compile

---

k8sprod.md

Envoy proxy also has the circuit breaker features and Istio uses the side car model and more

(proposing) Adding mention of Envoy and Istio

---

k8s101.md

typo fix: k8s101.md

---

README.md
firedrills.md

Ported from https://docs.google.com/document/d/1OyBqLovoYxdcpLozfatQorbC5X_Ey1h1KbWWaDE2vfs/edit?usp=sharing.

Add Gravity fire drills.

---

README.md

The requirements were pretty outdated.

Update requirements to latest versions.

---

docker.md

New changes for the Docker training part.

Docker training updates

---

docker.md

Fixed a few typos and content changes in docker section

Fixed a few typos and content changes in docker section

---

README.md
logging.md

Ported from https://docs.google.com/document/d/1ZWfyQxBwtiX2KP87CF5hn-JeAD1tQglJn6RTeaNAonc/edit?usp=sharing.

Add logging training.

---

firedrills.md

According to the topics a customer expressed interest in:
* How Planet container is configured.
* How to increase logging of certain components.
* How to collect only Kubernetes logs.

Add a few more things to firedrills.

---

README.md
monitoring-5.x.md
monitoring-6.x.md

Put together monitoring/alerts section for 6.X. Updated readme to clarify original training was for 5.5 and earlier.

Adding monitoring/alerts training 6.X

---

mattermost/postgres.yaml

Pinned PgSQL version to 12.2

---

env/Makefile
env/README.md
env/terraform/.gitignore
env/terraform/bootstrap-cluster-node.sh.tpl
env/terraform/cluster.tf
env/terraform/config.tf
env/terraform/network.tf
env/terraform/output.tf

Move a stripped down version of our training environment provisioning scripts to this repo so users/customers can use it as a reference when making their own environments.

Add environment provisioning scripts

---

README.md
gravity_upgrade.md

Initial commit for Gravity upgrade training. I've added the following:
- Intro to workshop
- Upgrade overview (stepping through each of the steps at a high level)
- Placeholders for the additional sections we discussed (gravity upgrade status, logs and more + exploring a gravity manual upgrade + section for upgrade scenarios)

Gravity upgrade training initial commit

---

upgrade/lab0.sh
upgrade/lab1.sh
upgrade/lab2-fix.sh
upgrade/lab2.sh
upgrade/lab3-fix.sh
upgrade/lab3.sh
upgrade/lab4.sh

@aelkugia @knisbet @eldios Take a look at the format folks, for the upgrade scenarios we discussed. You can follow the same format when working on other scenarios if you think it's ok.

Initial set of upgrade labs

---

gravity_upgrade.md

Working on adding my part of the training about logs and status messages.
Also fixed a couple stray line and spaces.

[WIP] Add Lele's part of the training about logs and status

---

gravity_upgrade.md
upgrade/lab2.sh
upgrade/lab3.sh
upgrade/lab4.sh
upgrade/lab5.sh
upgrade/lab6-fix.sh
upgrade/lab6.sh
upgrade/lab7-fix.sh
upgrade/lab7.sh

Added Scenario 5, 6 and 7 with a few additional common issues found during upgrades.
Also added a few minor text additions.

Add scenario 5, 6 and 7

---

docker.md

Fix broken link to low level details about capabilities

---

gravity101.md

Also added all the things I learned trying to do this on vagrant/virtualbox VMs.

Update with RAM requirements, changelog link, more

---

firedrills.md

~Updated upgrade command to the one that worked for me (not gravity upgrade, but just upgrade)~
Also fixed link to optimal cluster size docs

Fix link to optimal cluster size docs

---

gravity101.md
gravity101/v1-with-base/app.yaml
gravity101/v1-with-resources/app.yaml
gravity101/v1-with-resources/charts/alpine/Chart.yaml
gravity101/v1-with-resources/charts/alpine/templates/deployment.yaml
gravity101/v1-with-resources/charts/alpine/templates/pod.yaml
gravity101/v1/app.yaml
gravity101/v1/charts/alpine/Chart.yaml
gravity101/v1/charts/alpine/templates/deployment.yaml
gravity101/v1/charts/alpine/templates/pod.yaml
gravity101/v1/install.yaml
gravity101/v2/app.yaml
gravity101/v2/charts/alpine/Chart.yaml
gravity101/v2/charts/alpine/templates/deployment.yaml
gravity101/v2/charts/alpine/templates/pod.yaml
gravity101/v2/install.yaml
gravity101/v2/upgrade.yaml
gravity101/v3/app.yaml
gravity101/v3/charts/alpine/Chart.yaml
gravity101/v3/charts/alpine/templates/deployment.yaml
gravity101/v3/charts/alpine/templates/pod.yaml
gravity101/v3/install.yaml
gravity101/v3/upgrade.yaml

Modernization of Gravity 101 for Gravity 7.0.  See the commit messages/history for context on individual changes.

Gravity 101 updates
